// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Image content moderation flow using Genkit.
 *
 * - moderateImageContent - A function that moderates the content of an image.
 * - ModerateImageContentInput - The input type for the moderateImageContent function.
 * - ModerateImageContentOutput - The return type for the moderateImageContent function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ModerateImageContentInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      'A photo to be analyzed for inappropriate content, as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.' // Corrected the expected format
    ),
});

export type ModerateImageContentInput = z.infer<
  typeof ModerateImageContentInputSchema
>;

const ModerateImageContentOutputSchema = z.object({
  isAppropriate: z
    .boolean()
    .describe('Whether the image is appropriate for the ad platform.'),
  reasons: z
    .array(z.string())
    .describe('Reasons why the image might be considered inappropriate.'),
});

export type ModerateImageContentOutput = z.infer<
  typeof ModerateImageContentOutputSchema
>;

export async function moderateImageContent(
  input: ModerateImageContentInput
): Promise<ModerateImageContentOutput> {
  return moderateImageContentFlow(input);
}

const moderateImageContentPrompt = ai.definePrompt({
  name: 'moderateImageContentPrompt',
  input: {schema: ModerateImageContentInputSchema},
  output: {schema: ModerateImageContentOutputSchema},
  prompt: `You are an image moderation expert. Your job is to analyze images and determine if they are appropriate for an ad platform.

  Analyze the image provided, and consider the following:
  - Is the image sexually explicit?
  - Does the image contain hateful symbols or promote violence?
  - Does the image contain illegal activities?
  - Does the image contain any content that violates the ad platform's policies?

  Based on your analysis, determine if the image is appropriate for the ad platform. If it is not, provide reasons why it is not appropriate.

  Image: {{media url=photoDataUri}}
  \n\
  Output ONLY a JSON object that conforms to the schema. Do not include any other text.`, // Added instructions to output only a JSON object and included schema description
  config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_NONE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
    ],
  },
});

const moderateImageContentFlow = ai.defineFlow(
  {
    name: 'moderateImageContentFlow',
    inputSchema: ModerateImageContentInputSchema,
    outputSchema: ModerateImageContentOutputSchema,
  },
  async input => {
    const {output} = await moderateImageContentPrompt(input);
    return output!;
  }
);
