// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A semantic search flow to find relevant ads.
 *
 * - findRelevantAds - A function that takes a search query and a list of ads and returns the most relevant ones.
 * - FindRelevantAdsInput - The input type for the findRelevantAds function.
 * - FindRelevantAdsOutput - The return type for the findRelevantAds function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AdInfoSchema = z.object({
  id: z.string(),
  title: z.string(),
  description: z.string(),
});

const FindRelevantAdsInputSchema = z.object({
  query: z.string().describe('The user\'s search query.'),
  ads: z.array(AdInfoSchema).describe('A list of all available ads to search through.'),
});

export type FindRelevantAdsInput = z.infer<typeof FindRelevantAdsInputSchema>;

const FindRelevantAdsOutputSchema = z.object({
  relevantAdIds: z
    .array(z.string())
    .describe('An array of IDs of the ads that are most relevant to the user\'s query, ordered by relevance.'),
});

export type FindRelevantAdsOutput = z.infer<typeof FindRelevantAdsOutputSchema>;

export async function findRelevantAds(
  input: FindRelevantAdsInput
): Promise<FindRelevantAdsOutput> {
  return findRelevantAdsFlow(input);
}

const findRelevantAdsPrompt = ai.definePrompt({
  name: 'findRelevantAdsPrompt',
  input: {schema: FindRelevantAdsInputSchema},
  output: {schema: FindRelevantAdsOutputSchema},
  prompt: `You are a search expert for an online marketplace. Your task is to find the most relevant ads based on a user's search query.

  Instructions:
  1. Analyze the user's query: '{{query}}'. Understand the user's intent, even if the query is vague or contains typos.
  2. Compare the query against the titles and descriptions of the following available ads:
  {{#each ads}}
  - Ad ID: {{id}}
    Title: {{title}}
    Description: {{description}}
  {{/each}}
  3. Identify the ads that are the best semantic match for the query.
  4. Return a JSON object containing an array of the most relevant ad IDs, ordered from most to least relevant.

  Output ONLY a JSON object that conforms to the schema. Do not include any other text.`,
});


const findRelevantAdsFlow = ai.defineFlow(
  {
    name: 'findRelevantAdsFlow',
    inputSchema: FindRelevantAdsInputSchema,
    outputSchema: FindRelevantAdsOutputSchema,
  },
  async input => {
    if (input.ads.length === 0) {
      return { relevantAdIds: [] };
    }
    const {output} = await findRelevantAdsPrompt(input);
    return output!;
  }
);
