// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI flow to suggest a title and description for an ad based on an image and category.
 *
 * - suggestAdContent - A function that generates ad content suggestions.
 * - SuggestAdContentInput - The input type for the suggestAdContent function.
 * - SuggestAdContentOutput - The return type for the suggestAdContent function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestAdContentInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of the item for sale, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  category: z.string().describe('The category of the item.'),
  language: z.enum(['en', 'ar']).describe('The language for the output (en or ar).'),
});

export type SuggestAdContentInput = z.infer<typeof SuggestAdContentInputSchema>;

const SuggestAdContentOutputSchema = z.object({
  title: z
    .string()
    .describe('A catchy and descriptive title for the ad, in the specified language.'),
  description: z
    .string()
    .describe(
      'A detailed and appealing description for the ad, in the specified language.'
    ),
});

export type SuggestAdContentOutput = z.infer<typeof SuggestAdContentOutputSchema>;

export async function suggestAdContent(
  input: SuggestAdContentInput
): Promise<SuggestAdContentOutput> {
  return suggestAdContentFlow(input);
}

const suggestAdContentPrompt = ai.definePrompt({
  name: 'suggestAdContentPrompt',
  input: {schema: SuggestAdContentInputSchema},
  output: {schema: SuggestAdContentOutputSchema},
  prompt: `You are an expert copywriter for an online marketplace. Your task is to generate a compelling ad title and description based on an image, a category, and a language.

  Instructions:
  1.  Analyze the provided image to identify the main item, its key features, and its condition.
  2.  Consider the category: '{{category}}'.
  3.  Write the output in the specified language: '{{language}}'.
  4.  The title should be short, catchy, and include important keywords.
  5.  The description should be more detailed, highlighting the benefits and condition of the item. Be persuasive and friendly.

  Image: {{media url=photoDataUri}}
  \n\
  Output ONLY a JSON object that conforms to the schema. Do not include any other text.`,
});

const suggestAdContentFlow = ai.defineFlow(
  {
    name: 'suggestAdContentFlow',
    inputSchema: SuggestAdContentInputSchema,
    outputSchema: SuggestAdContentOutputSchema,
  },
  async input => {
    const {output} = await suggestAdContentPrompt(input);
    return output!;
  }
);
