import type { Ad, UserProfile } from '@/lib/types';

// بيانات متجر ملابس حريمي خليجي الافتراضي (20 منتج فاخر)
export const DEMO_GULF_STORE: UserProfile & { id: string } = {
  id: 'gulf-fashion-store-demo',
  name: 'دار الشيخة للأزياء والعبايات الخليجية',
  email: 'gulf.fashion@arb-soq.com',
  phone: '+966501234567',
  country: 'السعودية',
  city: 'الرياض',
  province: 'منطقة الرياض',
  village: 'حي العليا',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
  verified: true,
  role: 'user',
  status: 'active',
  walletBalance: 0,
  rating: 4.9,
  reviewCount: 128,
  store: {
    id: 'store-gulf-01',
    storeName: 'دار الشيخة للأزياء والعبايات الخليجية',
    storeDescription: 'أرقى تشكيلة من العبايات الخليجية الفاخرة، المخاوير الإماراتية، الجلابيات الكويتية، وفساتين الاستقبال والمناسبات بتصاميم تجمع بين الأصالة والفخامة العصرية. شحن لجميع دول الخليج والدول العربية.',
    coverImageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&auto=format&fit=crop&q=80',
    ownerId: 'gulf-fashion-store-demo',
  },
};

export const DEMO_GULF_PRODUCTS: Ad[] = [
  {
    id: 'gulf-prod-01',
    userId: 'gulf-fashion-store-demo',
    title: 'عباية ملكية كريب كوري أسود مطرزة يدوياً بالشك الفضي',
    description: 'عباية كلاسيكية راقية مصنوعة من الكريب الكوري الفاخر المسامي، مزينة بتطريز شك يدوي ناعم على الأكمام، تأتي مع طرحة مجانية متناسقة.',
    price: 380,
    category: 'fashion',
    subcategory: 'عبايات',
    imageUrls: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 340,
    clicks: 85,
    isPromoted: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 32,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-02',
    userId: 'gulf-fashion-store-demo',
    title: 'مخور إماراتي حرير طبيعي بتطريز تلي وزري أصلي',
    description: 'مخور إماراتي أصيل مصنوع من أجود خامات الحرير مع تطريز التلي الذهبي التراثي المتقن للمناسبات والأعياد.',
    price: 450,
    category: 'fashion',
    subcategory: 'مخاوير',
    imageUrls: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 412,
    clicks: 96,
    isPromoted: true,
    isFeatured: true,
    rating: 5.0,
    reviewCount: 41,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-03',
    userId: 'gulf-fashion-store-demo',
    title: 'جلابية استقبال كويتية مطرزة بالخيوط الذهبية واللؤلؤ',
    description: 'جلابية واسعة مريحة وراقية بتطريزات فخمة مناسبة للاستقبال والعزائم، قماش بارد وناعم غير شفاف.',
    price: 290,
    category: 'fashion',
    subcategory: 'جلابيات',
    imageUrls: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 290,
    clicks: 72,
    isPromoted: false,
    rating: 4.8,
    reviewCount: 22,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-04',
    userId: 'gulf-fashion-store-demo',
    title: 'عباية بشت خليجي مفتوحة بقماش الكتان ولون كحلي ملكي',
    description: 'قصة بشت عصرية فضفاضة تمنحك إطلالة مهيبة، خامة كتان فاخرة تناسب العمل والمناسبات الرسمية.',
    price: 340,
    category: 'fashion',
    subcategory: 'عبايات',
    imageUrls: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 310,
    clicks: 68,
    isPromoted: false,
    rating: 4.7,
    reviewCount: 19,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-05',
    userId: 'gulf-fashion-store-demo',
    title: 'فستان سهرة خليجي راقي شيفون مطرز للأعراس',
    description: 'فستان سهرة فخم بطبقات الشيفون الانسيابية مع حزام خصر مطرز بالكريستال اللامع وبطانة كاملة مريحة.',
    price: 520,
    category: 'fashion',
    subcategory: 'فساتين',
    imageUrls: ['https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 520,
    clicks: 140,
    isPromoted: true,
    rating: 5.0,
    reviewCount: 38,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-06',
    userId: 'gulf-fashion-store-demo',
    title: 'عباية كتف دبل كلوش بأكمام جاكار وتصميم عصري',
    description: 'عباية واسعة مريحة دبل كلوش تمنحك حرية الحركة مع أكمام منسوجة بنقوش الجاكار الراقية.',
    price: 310,
    category: 'fashion',
    subcategory: 'عبايات',
    imageUrls: ['https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 215,
    clicks: 50,
    isPromoted: false,
    rating: 4.6,
    reviewCount: 14,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-07',
    userId: 'gulf-fashion-store-demo',
    title: 'مخور كويتي قطن فاخر مطرز بنقوش تراثية ناعمة',
    description: 'قطن كويتي 100% عالي الجودة ومريح جداً للأجواء الصيفية مع تطريز صدري ناعم وثابت.',
    price: 240,
    category: 'fashion',
    subcategory: 'مخاوير',
    imageUrls: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 180,
    clicks: 42,
    isPromoted: false,
    rating: 4.8,
    reviewCount: 11,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-08',
    userId: 'gulf-fashion-store-demo',
    title: 'جلابية خليجية ميدي قطعتين بتطريز يدوي أنيق',
    description: 'تصميم مبتكر من قطعتين فستان داخلي مع كيب علوي شفاف ومطرز بتفاصيل جذابة.',
    price: 275,
    category: 'fashion',
    subcategory: 'جلابيات',
    imageUrls: ['https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 245,
    clicks: 61,
    isPromoted: false,
    rating: 4.9,
    reviewCount: 20,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-09',
    userId: 'gulf-fashion-store-demo',
    title: 'عباية ملونة حرير مغسول لون زمردي داكن مع طرحة',
    description: 'لمسة من التميز بألوان هادئة ومحتشمة، خامة حرير مغسول ناعم جداً وخفيف وبارد.',
    price: 360,
    category: 'fashion',
    subcategory: 'عبايات',
    imageUrls: ['https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 390,
    clicks: 98,
    isPromoted: false,
    rating: 4.9,
    reviewCount: 29,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-10',
    userId: 'gulf-fashion-store-demo',
    title: 'ثوب نشل بحريني تراثي مطرز بزري ذهبي أصيل',
    description: 'القطعة التراثية الخليجية الأشهر للمناسبات التراثية والاحتفالات، مطرز بالكامل بنقشات أصيلة.',
    price: 590,
    category: 'fashion',
    subcategory: 'فساتين',
    imageUrls: ['https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 450,
    clicks: 110,
    isPromoted: false,
    rating: 5.0,
    reviewCount: 35,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-11',
    userId: 'gulf-fashion-store-demo',
    title: 'قفطان شرقي خليجي مطرز بالسفيفة والعقد اليدوية',
    description: 'قفطان فخم بخامة كريب حريري مع حزام مميز وتطريز على طول الياقة والأكمام.',
    price: 430,
    category: 'fashion',
    subcategory: 'جلابيات',
    imageUrls: ['https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 320,
    clicks: 74,
    isPromoted: false,
    rating: 4.8,
    reviewCount: 18,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-12',
    userId: 'gulf-fashion-store-demo',
    title: 'عباية رأس خليجية قماش كريب سعودي سوبر ساتر',
    description: 'عباية رأس سابغة بقماش فاخر لا يشف وخفيف على الرأس بدون أن ينزلق مع ربطة مطاطية مريحة.',
    price: 250,
    category: 'fashion',
    subcategory: 'عبايات',
    imageUrls: ['https://images.unsplash.com/photo-1544441893-675973e31985?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 280,
    clicks: 65,
    isPromoted: false,
    rating: 4.7,
    reviewCount: 16,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-13',
    userId: 'gulf-fashion-store-demo',
    title: 'دراعة كويتية بتصميم كاجوال ناعم للمنزل والزيارات',
    description: 'خفيفة ومريحة وأنيقة في آن واحد، خامة قطنية مسامية بألوان ربيعية هادئة.',
    price: 195,
    category: 'fashion',
    subcategory: 'جلابيات',
    imageUrls: ['https://images.unsplash.com/photo-1485968579580-b6d095142e6e?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 195,
    clicks: 44,
    isPromoted: false,
    rating: 4.6,
    reviewCount: 12,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-14',
    userId: 'gulf-fashion-store-demo',
    title: 'عباية كتان كاجوال بأكمام مزمومة وجيوب مخفية',
    description: 'العباية المثالية للمشاوير والدوام اليومي، عملية وخفيفة مع تفاصيل زم على الأساور وجيوب عميقة.',
    price: 280,
    category: 'fashion',
    subcategory: 'عبايات',
    imageUrls: ['https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 260,
    clicks: 58,
    isPromoted: false,
    rating: 4.8,
    reviewCount: 17,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-15',
    userId: 'gulf-fashion-store-demo',
    title: 'فستان جلابية شيفون مطبع بنقوش ورود راقية وألوان زاهية',
    description: 'مزيج ساحر بين الفستان العصري والجلابية الشرقية، قماش شيفون مطبوع مع بطانة ناعمة وحزام خصر.',
    price: 220,
    category: 'fashion',
    subcategory: 'فساتين',
    imageUrls: ['https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 310,
    clicks: 70,
    isPromoted: false,
    rating: 4.7,
    reviewCount: 21,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-16',
    userId: 'gulf-fashion-store-demo',
    title: 'عباية فراشة وسيعة قماش صالونا ياباني أسود فاحم',
    description: 'قصة الفراشة الشهيرة المحبوبة، قماش صالونا ياباني أسود فاحم لا يبهت ولا يحتاج كوي متكرر.',
    price: 330,
    category: 'fashion',
    subcategory: 'عبايات',
    imageUrls: ['https://images.unsplash.com/photo-1520006403909-838d6b92c22e?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 290,
    clicks: 66,
    isPromoted: false,
    rating: 4.9,
    reviewCount: 25,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-17',
    userId: 'gulf-fashion-store-demo',
    title: 'مخور عماني أصيل بتطريز يدوي متقن وخيوط بريسم',
    description: 'قماش حرير قطني عماني مطرز يدوياً بنقشات بريسم كلاسيكية مع لمعة خفيفة تضفي فخامة استثنائية.',
    price: 410,
    category: 'fashion',
    subcategory: 'مخاوير',
    imageUrls: ['https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 240,
    clicks: 52,
    isPromoted: false,
    rating: 4.8,
    reviewCount: 15,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-18',
    userId: 'gulf-fashion-store-demo',
    title: 'شيلة خليجية ليزر فاخرة بشك طرفين وتطريز ناعم',
    description: 'طرحة وشيلة قماش ليزر ياباني ثابت غير قابل للانزلاق، مطرزة على الطرفين بشك يدوي ناعم.',
    price: 95,
    category: 'fashion',
    subcategory: 'شيل وطرح',
    imageUrls: ['https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 160,
    clicks: 38,
    isPromoted: false,
    rating: 4.9,
    reviewCount: 30,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-19',
    userId: 'gulf-fashion-store-demo',
    title: 'عباية مطرزة بالدانتيل الفرنسي الفاخر على الأكمام',
    description: 'عباية كريب لمسة حرير مع دانتيل فرنسي راقي على أطراف الأكمام والياقة لإطلالة مفعمة بالأنوثة.',
    price: 370,
    category: 'fashion',
    subcategory: 'عبايات',
    imageUrls: ['https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 375,
    clicks: 88,
    isPromoted: false,
    rating: 4.9,
    reviewCount: 27,
    postedAt: new Date().toISOString(),
  },
  {
    id: 'gulf-prod-20',
    userId: 'gulf-fashion-store-demo',
    title: 'طقم جلابية أم وبنتها مطرزة متناسقة للأعياد والمناسبات',
    description: 'طقم قطعتين متناسقتين للأم والابنة بتطريز زري ذهبي ناعم وخامة باردة مريحة ومبهجة للأعياد.',
    price: 480,
    category: 'fashion',
    subcategory: 'جلابيات',
    imageUrls: ['https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&auto=format&fit=crop&q=80'],
    condition: 'new',
    market: 'sa',
    currency: 'SAR',
    adType: 'sell-item',
    status: 'active',
    views: 480,
    clicks: 125,
    isPromoted: false,
    rating: 5.0,
    reviewCount: 44,
    postedAt: new Date().toISOString(),
  },
];
